Wf 111 push notifications backend
devLeaders/myNetflix pull request #71
Opened 2020-08-22 12:26 UTC by duch0416

Jeszcze sporo do zmiany ale już działa biore się teraz za hms

2020-08-26 13:46 UTC, dkolenda requested changes
Cofnij front z swoich comitów

2020-08-26 13:46 UTC, dkolenda commented on packages/backend/src/auth/users/user.dto.ts
> +
czemu masz tu jakas zmiane?

2020-08-26 13:46 UTC, dkolenda commented on packages/backend/src/auth/users/user.entity.ts
> +  OneToMany,
wylacz automatyczne formatowanie bo jestes podpisany przez to potem nawet w javowych androidowych plikach

2020-08-26 13:46 UTC, dkolenda commented on packages/backend/src/auth/auth.module.ts
> +  imports: [TypeOrmModule.forFeature([UserEntity, DevicesEntity])],
Czy dołączenie do modułu Auth DevicesEntity i NotificationService jest konieczne? Przez to moduł auth traci niezaleność

2020-08-26 13:46 UTC, dkolenda commented on packages/backend/src/auth/auth.service.ts
> +    if (!user)
wylacz formatowanie

2020-08-26 13:46 UTC, dkolenda commented on packages/backend/src/migration/1597939350680-notifications.ts
> +import {MigrationInterface, QueryRunner} from "typeorm";
czemu tych migratorów jest tyle?

2020-08-26 13:46 UTC, dkolenda commented on packages/backend/src/notifications/firebaseConfig.json
> +{
czemu to nie jest w env?

2020-08-26 13:46 UTC, dkolenda commented on packages/backend/src/notifications/firebaseConfig.json
> +{
Dodanie tego do ignora nie rozwiazuje problemu.

2020-08-28 08:49 UTC, Adamwojty requested changes
:(

2020-08-28 09:27 UTC, closed without merging